# Generated by Django 5.0.1 on 2024-01-09 11:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_article_auther'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 9, 11, 22, 0, 199974, tzinfo=datetime.timezone.utc)),
        ),
    ]
