# Generated by Django 5.0.1 on 2024-01-09 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_article_pub_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='pub_date',
        ),
    ]
