# Generated by Django 5.0.1 on 2024-01-10 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0002_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default=1, upload_to='images/profile'),
            preserve_default=False,
        ),
    ]
